# rename_ch09_scenes.ps1
# Renames the Ch9 narration scene files generated by ElevenLabs
# to NR_09_Scene_A.mp3 through NR_09_Scene_J.mp3
# Note: Scene D is split into D1 and D2 due to the 5000-char ElevenLabs v3 limit.
# D1 and D2 will be joined in Audacity during assembly.
#
# USAGE: Run from the repo root after ElevenLabs generation completes.
#   .\tools\rename_ch09_scenes.ps1

$outputDir = "C:\Users\aaron\Desktop"

Write-Host "Looking for files in: $outputDir" -ForegroundColor Cyan

# Delete any previously renamed NR_09_Scene_*.mp3 files
$existing = Get-ChildItem -Path $outputDir -Filter "NR_09_Scene_*.mp3"
if ($existing.Count -gt 0) {
    Write-Host "Removing $($existing.Count) existing NR_09_Scene_*.mp3 file(s)..." -ForegroundColor Yellow
    $existing | ForEach-Object {
        Remove-Item -LiteralPath $_.FullName -Force
        Write-Host "  Deleted: $($_.Name)" -ForegroundColor Yellow
    }
    Write-Host ""
}

# Scene labels and descriptions — 11 files (D is split into D1 + D2)
$sceneLabels = @("A", "B", "C", "D1", "D2", "E", "F", "G", "H", "I", "J")
$sceneNames = @(
    "A  -- Invocation Part 1",
    "B  -- Invocation Part 2",
    "C  -- Humility",
    "D1 -- Obedience Part 1",
    "D2 -- Obedience Part 2",
    "E  -- Compassion",
    "F  -- Teaching",
    "G  -- Meekness and Courage",
    "H  -- Justice and Mercy",
    "I  -- Joy and Beatitudes",
    "J  -- Benediction"
)

$expectedCount = 11

# Find all matching ElevenLabs tts_ files, sorted by creation time
$files = Get-ChildItem -Path $outputDir -Filter "tts_*.mp3" |
         Sort-Object CreationTime

if ($files.Count -eq 0) {
    Write-Host "No tts_*.mp3 files found at: $outputDir" -ForegroundColor Red
    exit 1
}

if ($files.Count -ne $expectedCount) {
    Write-Host "Expected $expectedCount scene files, found $($files.Count)." -ForegroundColor Yellow
    Write-Host "Files found:"
    $files | ForEach-Object { Write-Host "  $($_.Name)  [Created: $($_.CreationTime)]" }
    Write-Host ""
    $confirm = Read-Host "Proceed with renaming the $($files.Count) file(s) found? (y/n)"
    if ($confirm -ne "y") {
        Write-Host "Aborted." -ForegroundColor Red
        exit 1
    }
}

Write-Host ""
Write-Host "Renaming Ch9 narration scene files..." -ForegroundColor Cyan
Write-Host ""

$errors = 0
for ($i = 0; $i -lt [Math]::Min($files.Count, $expectedCount); $i++) {
    $srcPath  = $files[$i].FullName
    $destName = "NR_09_Scene_$($sceneLabels[$i]).mp3"
    $destPath = Join-Path $outputDir $destName

    if (Test-Path -LiteralPath $destPath) {
        Write-Host "  SKIP  $($sceneNames[$i]) -- destination already exists: $destName" -ForegroundColor Yellow
        continue
    }

    try {
        Rename-Item -LiteralPath $srcPath -NewName $destName -ErrorAction Stop
        Write-Host "  OK    Scene $($sceneNames[$i])" -ForegroundColor Green
    } catch {
        Write-Host "  FAIL  Scene $($sceneNames[$i]) -- $($_.Exception.Message)" -ForegroundColor Red
        $errors++
    }
}

Write-Host ""
if ($errors -eq 0) {
    Write-Host "All scenes renamed successfully." -ForegroundColor Green
    Write-Host ""
    Write-Host "Files ready for Audacity assembly:"
    Get-ChildItem -Path $outputDir -Filter "NR_09_Scene_*.mp3" |
        Sort-Object Name |
        ForEach-Object { Write-Host "  $($_.Name)" }
    Write-Host ""
    Write-Host "NOTE: D1 + D2 should be joined as a single Scene D track in Audacity." -ForegroundColor Cyan
} else {
    Write-Host "$errors error(s) encountered. Check output above." -ForegroundColor Red
}
